# =============================================================================
# analysis.R
# Workshop 2: Screen Based Eye Tracking of Television Commercials, analysis session
# Martin's Family Clothing Consumer Behavior Research Laboratory, JSU
#
# SIMULATED DATA. Every number this script reads was generated by
# make_simulated_data.py (seed 20268242). No viewer was recorded. The design follows
# the structure of the iMotions demonstration study "DEMO - SonyBravia" (one brand,
# two television commercials, a screen based eye tracker) and nothing else about it.
#
# Design: WITHIN subjects. Every respondent watched both commercials
# (Commercial_1_Balls and Commercial_2_Paint, 60 s each) on the lab monitor with the
# Smart Eye Aurora (60 Hz). The Group column is the ORDER (A = Balls first,
# B = Paint first), not a treatment. Workshop 1 compared two groups of people
# (Welch t test); this workshop compares two commercials within the same people
# (paired t test), and the order of viewing becomes a nuisance factor to check.
#
# What the script does, in order:
#   0. Load packages and set paths and the figure theme
#   1. Read the simulated Individual AOI metrics export, the survey, and the log
#   2. Clean: apply the exclusion rule, treat never fixated AOIs correctly
#   3. Descriptive table by commercial and AOI (mean, SD, n, respondent ratio)
#   4. H1: Product_TV Dwell time (%), Balls versus Paint (paired t test, d_z, Wilcoxon)
#   5. H2: Brand_Logo TTFF AOI (ms), Balls versus Paint (paired t test on respondents
#      with both values, respondent ratio, sensitivity analysis for never fixators)
#   6. H3: Liking, Balls versus Paint (paired t test), preference counts
#   7. Order effect: Product_TV dwell_pct ~ commercial * order_position + (1 | respondent)
#   8. Brand_Logo dwell time and brand recall (point biserial correlation)
#   9. Assumption checks (plots saved to figures/)
#  10. Three report figures saved as PNG, 1400 px wide, 150 dpi
#
# Sign convention: every difference is Paint MINUS Balls (Commercial_2 minus
# Commercial_1). A positive difference means the Paint value is larger.
#
# How to run (either way works):
#   a) In RStudio: open this file, set the working directory to the folder that
#      holds the CSV files (Session > Set Working Directory > To Source File
#      Location), then Source.
#   b) From a terminal, inside the data folder:  Rscript analysis.R
# The console output is also written to analysis_output.txt next to the data.
#
# Packages used: readr, dplyr, tidyr, ggplot2, lme4. Optional: lmerTest (gives
# p values for the mixed model), effectsize (noncentral t confidence interval
# for Cohen's d_z). If a package is missing, run once in the console:
#   install.packages(c("readr", "dplyr", "tidyr", "ggplot2", "lme4",
#                      "lmerTest", "effectsize"))
# =============================================================================

# ---- 0. Setup ---------------------------------------------------------------
suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(lme4)
})
has_lmerTest   <- requireNamespace("lmerTest",   quietly = TRUE)
has_effectsize <- requireNamespace("effectsize", quietly = TRUE)

# Find the folder that holds this script, so the CSV paths work in RStudio and
# from Rscript alike. Falls back to the current working directory.
script_dir <- tryCatch({
  args <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", args[grep("^--file=", args)])
  if (length(f) == 1) dirname(normalizePath(f)) else getwd()
}, error = function(e) getwd())
setwd(script_dir)
fig_dir <- file.path(script_dir, "figures")
dir.create(fig_dir, showWarnings = FALSE)

# Save the console output next to the data. split = TRUE keeps it on screen too.
output_file <- file.path(script_dir, "analysis_output.txt")
sink(output_file, split = TRUE)
cat("SIMULATED ad test analysis, run on", format(Sys.time(), "%Y-%m-%d %H:%M"), "\n")
cat("R", R.version$major, ".", R.version$minor, "; lme4 ", as.character(packageVersion("lme4")),
    "; lmerTest available: ", has_lmerTest, "; effectsize available: ", has_effectsize, "\n\n", sep = "")

# Palette: navy (Paint), gray (Balls), one accent for the means and intervals.
# Legends and direct labels carry the identity as well, so color is never the only cue.
col_paint  <- "#1F3864"
col_balls  <- "#8C8C8C"
col_accent <- "#A6561A"
comm_colors <- c(Balls = col_balls, Paint = col_paint)
comm_levels <- c("Balls", "Paint")        # Commercial_1 first, Commercial_2 second
aoi_levels  <- c("Product_TV", "Brand_Logo", "Tagline_Text", "Hero_Element")

theme_ad <- function(base_size = 13) {
  theme_minimal(base_size = base_size) +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_line(color = "#E3E3E3", linewidth = 0.4),
          axis.line.x = element_line(color = "#B0B0B0", linewidth = 0.4),
          plot.title = element_text(face = "bold", size = base_size + 2),
          plot.subtitle = element_text(color = "#555555"),
          plot.caption = element_text(color = "#777777", size = base_size - 3, hjust = 0),
          legend.position = "top",
          legend.title = element_blank(),
          plot.background = element_rect(fill = "white", color = NA))
}
save_fig <- function(plot, name, height_px = 900) {
  # 1400 px wide at 150 dpi = 9.33 in wide
  ggsave(file.path(fig_dir, name), plot, width = 1400 / 150, height = height_px / 150,
         dpi = 150, bg = "white")
  cat("saved figure:", file.path("figures", name), "\n")
}
f2 <- function(x) sprintf("%.2f", x)
fp <- function(p) ifelse(p < .001, "p < .001", paste0("p = ", sub("^0", "", sprintf("%.3f", p))))
# p value for the output file: five decimals (so a value such as .0465 cannot be rounded two ways),
# scientific notation below 0.0001 so no p prints as 0.00000
pf <- function(p) ifelse(p < 0.0001, sprintf("%.2e", p), sprintf("%.5f", p))

# ---- 1. Read the files ------------------------------------------------------
# Line 1 of every file is a "# SIMULATED" comment, so comment = "#" skips it.
# iMotions writes NA when a metric cannot be calculated (for example, the
# respondent never fixated the AOI), so na = "NA".
aoi_raw <- read_csv("SIMULATED_ad_test_AOI_metrics.csv", comment = "#",
                    na = c("NA", ""), show_col_types = FALSE)
survey  <- read_csv("SIMULATED_ad_test_survey.csv",  comment = "#", show_col_types = FALSE)
session <- read_csv("SIMULATED_ad_test_session_log.csv", comment = "#", show_col_types = FALSE)

cat("---- 1. Files read ----\n")
cat("AOI metrics rows:", nrow(aoi_raw), " respondents:", n_distinct(aoi_raw$`Respondent Name`),
    " stimuli:", paste(unique(aoi_raw$Stimulus), collapse = ", "),
    " AOIs:", paste(unique(aoi_raw$`AOI Name`), collapse = ", "), "\n")
cat("Survey rows:", nrow(survey), "  Session log rows:", nrow(session), "\n\n")

# Rename the iMotions column names to short R friendly names. Keep this block as
# the one place where the mapping from export header to variable lives.
aoi <- aoi_raw %>%
  rename(respondent   = `Respondent Name`,
         order        = Group,
         sex          = Gender,
         age          = Age,
         session_date = `Session Date`,
         stimulus     = Stimulus,
         aoi          = `AOI Name`,
         stim_dur_ms  = `Stimulus duration`,
         aoi_dur_ms   = `AOI duration (ms)`,
         aoi_dur_pct  = `AOI duration (%)`,
         valid_pct    = `Valid data`,
         hit_time_ms  = `Gaze Hit time AOI (ms)`,
         fix_count    = `Fixation count`,
         revisits     = `Revisit count`,
         ttff_aoi_ms  = `TTFF AOI (ms)`,
         ttff_par_ms  = `TTFF parent (ms)`,
         ttff_max_ms  = `TTFF max. (ms)`,
         dwell_ms     = `Dwell time (ms)`,
         dwell_pct    = `Dwell time (%)`,
         fix_dur_ms   = `Fixation duration (ms)`) %>%
  mutate(commercial = factor(recode(stimulus, Commercial_1_Balls = "Balls", Commercial_2_Paint = "Paint"),
                             levels = comm_levels),
         # Position of the commercial in the viewing sequence, derived from the order
         # group: Group A saw Balls first, Group B saw Paint first.
         order_position = factor(if_else((order == "A") == (commercial == "Balls"), "first", "second"),
                                 levels = c("first", "second")),
         aoi = factor(aoi, levels = aoi_levels))

# ---- 2. Clean ---------------------------------------------------------------
# Exclusion rule, fixed before data collection: Valid data below 70 percent.
# Valid data is an Information metric (percentage of collected and interpolated
# samples). On screen based data it is the first screen for tracking quality.
excluded <- aoi %>% filter(valid_pct < 70) %>% distinct(respondent, order, valid_pct)
cat("---- 2. Cleaning ----\n")
cat("Excluded (Valid data < 70 percent):\n"); print(as.data.frame(excluded))
cat("Session log says for these respondents:\n")
print(as.data.frame(session %>% filter(`Respondent Name` %in% excluded$respondent) %>%
                      select(`Respondent Name`, `Calibration result`, Recalibrations, `Data complete`)))
cat("Decision note:", session$`Decision note`[session$`Respondent Name` %in% excluded$respondent], "\n")

aoi_clean <- aoi %>%
  filter(valid_pct >= 70) %>%
  mutate(
    fixated   = !is.na(ttff_aoi_ms),             # TRUE when at least one fixation hit the AOI
    # A never fixated AOI has no TTFF: it stays NA ("not observed"). It does have a
    # dwell time, which is zero. The same logic applies to the fixation count.
    dwell_ms  = if_else(is.na(dwell_ms), 0, dwell_ms),
    dwell_pct = if_else(is.na(dwell_pct), 0, dwell_pct),
    fix_count = if_else(is.na(fix_count), 0L, as.integer(fix_count)),
    revisits  = if_else(is.na(revisits), 0L, as.integer(revisits)),
    dwell_s   = dwell_ms / 1000)

n_by_order <- aoi_clean %>% distinct(respondent, order) %>% count(order)
cat("\nRespondents kept per order group (A = Balls first, B = Paint first):\n"); print(as.data.frame(n_by_order))
cat("Respondents kept:", n_distinct(aoi_clean$respondent), "\n")
cat("Rows with no fixation on the AOI (TTFF not observed, dwell set to 0):",
    sum(!aoi_clean$fixated), "of", nrow(aoi_clean), "\n")
nf <- aoi_clean %>% filter(!fixated) %>% count(commercial, aoi)
cat("Never fixated rows by commercial and AOI:\n"); print(as.data.frame(nf), row.names = FALSE)
cat("TTFF max. (ms) on the never fixated rows (AOI Metrics article: the parent's presentation duration):",
    paste(sort(unique(aoi_clean$ttff_max_ms[!aoi_clean$fixated])), collapse = ", "), "\n\n")

# ---- 3. Descriptive table by commercial and AOI -----------------------------
# TTFF AOI: mean and SD over respondents who fixated the AOI (n_ttff).
# Dwell share and fixation count: all kept respondents (zeros included).
# Respondent ratio (%): share of respondents with at least one fixation, which
# is the fixation based "Respondent ratio (%)" metric in the iMotions table.
# Fixation duration: over rows with at least one fixation.
desc <- aoi_clean %>%
  group_by(aoi, commercial) %>%
  summarise(aoi_active_ms = first(aoi_dur_ms),
            n = n(),
            resp_ratio_pct = round(100 * mean(fixated), 1),
            n_ttff   = sum(fixated),
            ttff_aoi_mean_ms = mean(ttff_aoi_ms, na.rm = TRUE),
            ttff_aoi_sd_ms   = sd(ttff_aoi_ms, na.rm = TRUE),
            dwell_mean_pct = mean(dwell_pct),
            dwell_sd_pct   = sd(dwell_pct),
            dwell_mean_ms  = mean(dwell_ms),
            fix_mean = mean(fix_count),
            fix_sd   = sd(fix_count),
            fixdur_mean_ms = mean(fix_dur_ms, na.rm = TRUE),
            .groups = "drop") %>%
  mutate(across(where(is.double), ~ round(.x, 2))) %>%
  arrange(aoi, commercial)
cat("---- 3. Descriptive table by AOI and commercial ----\n")
print(as.data.frame(desc), row.names = FALSE)
write_csv(desc, "SIMULATED_descriptives_by_commercial_AOI.csv")
cat("written: SIMULATED_descriptives_by_commercial_AOI.csv\n\n")

# Realized versus planned: any one sample of 29 drifts from its model.
fx <- aoi_clean %>% filter(fixated)
cat("Realized versus planned (generator assumptions in make_simulated_data.py):\n")
cat(sprintf("  Fixations per second of dwell: %.2f (planned about 3.4 to 3.5)\n", sum(fx$fix_count) / sum(fx$dwell_s)))
cat(sprintf("  Fixation duration (ms), rows with a fixation: M = %.0f, SD = %.0f (planned about 290, 60)\n",
            mean(fx$fix_dur_ms), sd(fx$fix_dur_ms)))
pd <- desc %>% filter(aoi == "Product_TV") %>% pull(dwell_mean_pct)
cat(sprintf("  Product_TV Dwell time (%%): Balls %.1f, Paint %.1f (planned 22, 29)\n", pd[1], pd[2]))
cat(sprintf("  Hero_Element Dwell time (%%): Balls %.1f, Paint %.1f (planned 55, 48)\n",
            desc$dwell_mean_pct[desc$aoi == "Hero_Element"][1], desc$dwell_mean_pct[desc$aoi == "Hero_Element"][2]))
cat(sprintf("  Tagline_Text Dwell time (%%): Balls %.1f, Paint %.1f (planned about 30)\n\n",
            desc$dwell_mean_pct[desc$aoi == "Tagline_Text"][1], desc$dwell_mean_pct[desc$aoi == "Tagline_Text"][2]))

# ---- Helper: paired t test plus Cohen's d_z with a 95 percent CI ------------
# The difference is Paint minus Balls. Cohen's d_z = mean difference / SD of the
# differences, the effect size that goes with a paired t test (t = d_z * sqrt(n)).
# The CI comes from effectsize::cohens_d on the differences (noncentral t method)
# when the package is installed; otherwise from the large sample approximation
# SE(d_z) = sqrt(1 / n + d_z^2 / (2 n)). Pairs with a missing value are dropped.
report_paired <- function(x_balls, x_paint, label, unit) {
  ok <- !is.na(x_balls) & !is.na(x_paint)
  b <- x_balls[ok]; p <- x_paint[ok]; dif <- p - b; n <- length(dif)
  tt <- t.test(p, b, paired = TRUE)
  dz <- mean(dif) / sd(dif)
  if (has_effectsize) {
    es <- effectsize::cohens_d(dif, ci = 0.95)
    stopifnot(abs(es$Cohens_d - dz) < 1e-8)
    dz_lo <- es$CI_low; dz_hi <- es$CI_high; ci_method <- "noncentral t (effectsize)"
  } else {
    se_d <- sqrt(1 / n + dz^2 / (2 * n))
    dz_lo <- dz - 1.96 * se_d; dz_hi <- dz + 1.96 * se_d; ci_method <- "large sample approximation"
  }
  wx <- suppressWarnings(wilcox.test(p, b, paired = TRUE, exact = FALSE))
  cat(sprintf("%s\n", label))
  cat(sprintf("  Balls: M = %.2f %s, SD = %.2f, n = %d\n", mean(b), unit, sd(b), n))
  cat(sprintf("  Paint: M = %.2f %s, SD = %.2f, n = %d\n", mean(p), unit, sd(p), n))
  cat(sprintf("  Mean difference (Paint minus Balls) = %.2f %s, SD of differences = %.2f, 95%% CI [%.2f, %.2f]\n",
              mean(dif), unit, sd(dif), tt$conf.int[1], tt$conf.int[2]))
  cat(sprintf("  Paired t(%d) = %.2f, p = %s\n", as.integer(tt$parameter), tt$statistic, pf(tt$p.value)))
  cat(sprintf("  Cohen's d_z = %.2f, 95%% CI [%.2f, %.2f]  (%s)\n", dz, dz_lo, dz_hi, ci_method))
  cat(sprintf("  Wilcoxon signed rank V = %.0f, p = %s\n", wx$statistic, pf(wx$p.value)))
  cat(sprintf("  Shapiro Wilk on the differences: W = %.3f, p = %.3f\n\n",
              shapiro.test(dif)$statistic, shapiro.test(dif)$p.value))
  invisible(list(label = label, n = n, m_b = mean(b), m_p = mean(p), sd_b = sd(b), sd_p = sd(p),
                 diff = mean(dif), sd_diff = sd(dif), ci_lo = tt$conf.int[1], ci_hi = tt$conf.int[2],
                 t = unname(tt$statistic), df = unname(tt$parameter), p = tt$p.value,
                 dz = dz, dz_lo = dz_lo, dz_hi = dz_hi, V = unname(wx$statistic), p_w = wx$p.value,
                 shapiro_p = shapiro.test(dif)$p.value, dif = dif))
}

# ---- 4. H1: Product_TV Dwell time (%) ---------------------------------------
# H1: Paint, which shows the television in more of its running time, draws a larger
# share of fixation based dwell time on Product_TV than Balls does. Every kept
# respondent fixated Product_TV in both commercials, so n = the number of kept
# respondents. Dwell time (%) is relative to the time the AOI was active
# (14 s in Balls, 20 s in Paint), so the two shares are on a common scale.
cat("---- 4. H1: Product_TV Dwell time (%), Balls versus Paint (paired) ----\n")
ptv <- aoi_clean %>% filter(aoi == "Product_TV")
ptv_w <- ptv %>% select(respondent, order, commercial, dwell_pct) %>%
  pivot_wider(names_from = commercial, values_from = dwell_pct)
res_h1 <- report_paired(ptv_w$Balls, ptv_w$Paint, "Product_TV Dwell time (%) (all kept respondents)", "%")

# ---- 5. H2: Brand_Logo TTFF AOI (ms) ----------------------------------------
# H2: the time from the end card onset to the first fixation on the logo differs
# between the commercials. Only respondents who fixated the logo in BOTH commercials
# contribute a pair, so n is below the number of kept respondents. TTFF AOI counts
# from the AOI's start, which here is the start of the end card.
cat("---- 5. H2: Brand_Logo TTFF AOI (ms), Balls versus Paint (paired) ----\n")
logo <- aoi_clean %>% filter(aoi == "Brand_Logo")
logo_w <- logo %>% select(respondent, order, commercial, ttff_aoi_ms) %>%
  pivot_wider(names_from = commercial, values_from = ttff_aoi_ms)
cat("Respondent ratio (% of kept respondents who fixated the logo):\n")
cat(sprintf("  Balls: %d of %d (%.1f%%)\n", sum(!is.na(logo_w$Balls)), nrow(logo_w), 100 * mean(!is.na(logo_w$Balls))))
cat(sprintf("  Paint: %d of %d (%.1f%%)\n", sum(!is.na(logo_w$Paint)), nrow(logo_w), 100 * mean(!is.na(logo_w$Paint))))
tab_fix <- table(Balls = factor(!is.na(logo_w$Balls), levels = c(TRUE, FALSE)),
                 Paint = factor(!is.na(logo_w$Paint), levels = c(TRUE, FALSE)))
cat("Fixated the logo (TRUE) or never fixated it (FALSE), rows = Balls, columns = Paint:\n"); print(tab_fix)
only_b <- tab_fix["TRUE", "FALSE"]; only_p <- tab_fix["FALSE", "TRUE"]
cat(sprintf("Respondents with a TTFF in both commercials (the pairs): %d\n", tab_fix["TRUE", "TRUE"]))
if (only_b + only_p > 0) {
  bt <- binom.test(only_b, only_b + only_p, 0.5)
  cat(sprintf("Exact McNemar test of the two respondent ratios (%d fixated only Balls, %d only Paint): p = %.3f\n\n",
              only_b, only_p, bt$p.value))
}
res_h2 <- report_paired(logo_w$Balls, logo_w$Paint,
                        "Brand_Logo TTFF AOI (ms) (respondents with a TTFF in both commercials)", "ms")

# Sensitivity (H2b): keep the never fixators by assigning them the AOI's active
# duration (5000 ms, the longest possible TTFF AOI). This is an analysis choice, not
# the iMotions export column: the TTFF max. (ms) metric counts from the start of the
# parent (the commercial) and assigns the parent's duration (60000 ms), so it is not
# used here.
cat("---- 5b. H2b sensitivity: never fixators assigned the AOI active duration (5000 ms) ----\n")
logo_cens <- logo_w %>% mutate(Balls = replace_na(Balls, 5000), Paint = replace_na(Paint, 5000))
res_h2b <- report_paired(logo_cens$Balls, logo_cens$Paint,
                         "Brand_Logo TTFF AOI (ms), never fixated coded 5000 (all kept respondents)", "ms")

# ---- 6. H3: Liking -----------------------------------------------------------
# H3: the commercials differ in liking. Collected on the survey slide after each
# commercial. The ratings are whole numbers from 1 to 7, so the Wilcoxon signed
# rank test is a natural companion to the paired t test.
cat("---- 6. H3: Liking (1 to 7), Balls versus Paint (paired) ----\n")
survey_clean <- survey %>%
  rename(respondent = `Respondent Name`, order = Group,
         liking_balls = Liking_Balls_1to7, liking_paint = Liking_Paint_1to7,
         recall = Brand_recall, preferred = Ad_preferred) %>%
  filter(!respondent %in% excluded$respondent)
res_h3 <- report_paired(survey_clean$liking_balls, survey_clean$liking_paint,
                        "Liking of the commercial (1 to 7)", "points")
cat("Ad_preferred (counts):\n"); tab_pref <- table(survey_clean$preferred); print(tab_pref)
bp <- binom.test(unname(tab_pref["Balls"]), sum(tab_pref), 0.5)
cat(sprintf("Exact binomial test of an even split: %d of %d preferred Balls (%.1f%%), 95%% CI [%.1f%%, %.1f%%], p = %.3f\n\n",
            tab_pref["Balls"], sum(tab_pref), 100 * unname(tab_pref["Balls"]) / sum(tab_pref),
            100 * bp$conf.int[1], 100 * bp$conf.int[2], bp$p.value))

# Attention versus attitude (exploratory): does the respondent who gave more
# Product_TV attention to Paint than to Balls also like Paint more?
link <- ptv_w %>% mutate(dwell_diff = Paint - Balls) %>%
  inner_join(survey_clean %>% mutate(liking_diff = liking_paint - liking_balls), by = c("respondent", "order"))
ct_dis <- cor.test(link$dwell_diff, link$liking_diff)
cat(sprintf("Exploratory: correlation of the Product_TV dwell difference with the liking difference (both Paint minus Balls): r = %.2f, 95%% CI [%.2f, %.2f], p = %.3f\n",
            ct_dis$estimate, ct_dis$conf.int[1], ct_dis$conf.int[2], ct_dis$p.value))
cat(sprintf("Paint drew more Product_TV attention than Balls for %d of %d respondents. On liking, %d rated Balls higher, %d rated Paint higher, and %d gave equal ratings.\n\n",
            sum(link$dwell_diff > 0), nrow(link), sum(link$liking_diff < 0), sum(link$liking_diff > 0), sum(link$liking_diff == 0)))

# ---- 7. Order effect: mixed model on Product_TV dwell share ------------------
# Each respondent contributes two Product_TV dwell shares (one per commercial), so
# the rows are not independent. A random intercept for respondent absorbs the
# viewer level tendency to look longer or shorter overall. order_position says
# whether the commercial was seen first or second; the generator built in a
# carryover of +3 percentage points for the commercial seen second.
# The two factors are coded -0.5 / +0.5 (commercial: Balls = -0.5, Paint = +0.5;
# order_position: first = -0.5, second = +0.5), so each coefficient is the full
# difference between the two levels, averaged over the other factor:
#   commercial1                  = Paint minus Balls
#   order_position1              = second minus first (the order effect)
#   commercial1:order_position1  = difference of differences
# Because Group (A or B) fixes which commercial is first, the interaction is the same
# contrast as the A versus B difference in a viewer's total Product_TV dwell, so it is
# a between respondents comparison and has its own (smaller) degrees of freedom.
cat("---- 7. Mixed model: Product_TV dwell_pct ~ commercial * order_position + (1 | respondent) ----\n")
mm_data <- ptv %>% select(respondent, order, commercial, order_position, dwell_pct) %>% as.data.frame()
contrasts(mm_data$commercial)     <- c(-0.5, 0.5)
contrasts(mm_data$order_position) <- c(-0.5, 0.5)
if (has_lmerTest) {
  mm <- lmerTest::lmer(dwell_pct ~ commercial * order_position + (1 | respondent), data = mm_data, REML = TRUE)
  print(summary(mm, correlation = FALSE))
  cat("\nType III tests (Satterthwaite degrees of freedom):\n")
  print(anova(mm, type = 3))
} else {
  mm <- lme4::lmer(dwell_pct ~ commercial * order_position + (1 | respondent), data = mm_data, REML = TRUE)
  print(summary(mm, correlation = FALSE))
  cat("\nlmerTest is not installed, so no p values are printed. A |t| above about 2\n",
      "is the usual rough guide; install lmerTest for Satterthwaite p values.\n")
}
cf <- as.data.frame(coef(summary(mm)))
if (has_lmerTest) {
  names(cf) <- c("est", "se", "df", "t", "p")
  cf$ci_lo <- cf$est - qt(0.975, cf$df) * cf$se
  cf$ci_hi <- cf$est + qt(0.975, cf$df) * cf$se
} else {
  names(cf) <- c("est", "se", "t")
  cf$df <- NA_real_; cf$p <- NA_real_; cf$ci_lo <- cf$est - 1.96 * cf$se; cf$ci_hi <- cf$est + 1.96 * cf$se
}
term_labels <- c("(Intercept)" = "Intercept (grand mean)",
                 "commercial1" = "Commercial (Paint minus Balls)",
                 "order_position1" = "Order position (second minus first)",
                 "commercial1:order_position1" = "Commercial x order position")
cat("\nFixed effects with 95% CI (estimate +/- t(Satterthwaite df) x SE):\n")
for (nm in rownames(cf)) {
  cat(sprintf("  %-38s b = %6.2f, SE = %.2f, df = %5.1f, t = %6.2f, p = %s, 95%% CI [%.2f, %.2f]\n",
              term_labels[[nm]], cf[nm, "est"], cf[nm, "se"], cf[nm, "df"], cf[nm, "t"], pf(cf[nm, "p"]),
              cf[nm, "ci_lo"], cf[nm, "ci_hi"]))
}
# Intraclass correlation: the share of the variance in dwell share that lies between
# viewers. Adjusted ICC = viewer variance / (viewer variance + residual variance) in
# the fitted model; the unconditional ICC comes from the model with no fixed effects.
vc <- as.data.frame(VarCorr(mm))
var_resp <- vc$vcov[vc$grp == "respondent"]; var_res <- vc$vcov[vc$grp == "Residual"]
icc_adj <- var_resp / (var_resp + var_res)
mm0 <- lme4::lmer(dwell_pct ~ 1 + (1 | respondent), data = mm_data, REML = TRUE)
vc0 <- as.data.frame(VarCorr(mm0))
icc_null <- vc0$vcov[vc0$grp == "respondent"] / sum(vc0$vcov)
cat(sprintf("\nICC (adjusted, from the fitted model) = %.3f  (respondent variance %.2f, residual variance %.2f)\n",
            icc_adj, var_resp, var_res))
cat(sprintf("ICC (unconditional, intercept only model) = %.3f\n", icc_null))
cat(sprintf("Correlation of a respondent's two Product_TV dwell shares (raw): r = %.2f\n", cor(ptv_w$Balls, ptv_w$Paint)))

# A simple within respondent estimate of the order effect, which Excel can reproduce:
# Paint minus Balls is (commercial effect + order effect) for Group A (Paint second)
# and (commercial effect - order effect) for Group B (Paint first).
dA <- res_h1$dif[ptv_w$order == "A"]; dB <- res_h1$dif[ptv_w$order == "B"]
order_simple <- (mean(dA) - mean(dB)) / 2
cat(sprintf("Simple estimate of the order effect = (mean difference in Group A - mean difference in Group B) / 2 = (%.2f - %.2f) / 2 = %.2f (n = %d and %d)\n",
            mean(dA), mean(dB), order_simple, length(dA), length(dB)))
cell_means <- ptv %>% group_by(commercial, order_position) %>%
  summarise(n = n(), mean_pct = round(mean(dwell_pct), 2), sd_pct = round(sd(dwell_pct), 2), .groups = "drop")
cat("\nRaw cell means of Product_TV Dwell time (%):\n"); print(as.data.frame(cell_means), row.names = FALSE)
cat("\n")

# ---- 8. Brand_Logo dwell time and brand recall -------------------------------
# Brand_recall is one answer per respondent, so the logo attention measure is
# also one number per respondent: the total fixation based Dwell time (ms) on
# Brand_Logo over the two commercials (a never fixated logo counts as 0 ms).
# Recall is coded 1 = Yes, 0 = No. The Pearson correlation of a continuous
# variable with a 0/1 variable is the point biserial correlation.
cat("---- 8. Brand_Logo dwell time and brand recall (point biserial) ----\n")
logo_tot <- logo %>% group_by(respondent) %>%
  summarise(logo_dwell_ms = sum(dwell_ms), .groups = "drop") %>%
  inner_join(survey_clean %>% select(respondent, recall), by = "respondent") %>%
  mutate(recall01 = as.integer(recall == "Yes"))
tab_rec <- table(logo_tot$recall)
cat(sprintf("Brand recall: %d Yes and %d No of %d (%.1f%% Yes)\n", tab_rec["Yes"], tab_rec["No"],
            nrow(logo_tot), 100 * tab_rec["Yes"] / nrow(logo_tot)))
rg <- logo_tot %>% group_by(recall) %>%
  summarise(n = n(), mean_ms = round(mean(logo_dwell_ms), 0), sd_ms = round(sd(logo_dwell_ms), 0), .groups = "drop")
cat("Total Brand_Logo Dwell time (ms) by recall:\n"); print(as.data.frame(rg), row.names = FALSE)
ct_rec <- cor.test(logo_tot$logo_dwell_ms, logo_tot$recall01)
cat(sprintf("Point biserial correlation: r_pb(%d) = %.2f, 95%% CI [%.2f, %.2f], p = %s\n",
            as.integer(ct_rec$parameter), ct_rec$estimate, ct_rec$conf.int[1], ct_rec$conf.int[2], pf(ct_rec$p.value)))
mw <- suppressWarnings(wilcox.test(logo_dwell_ms ~ recall, data = logo_tot, exact = FALSE))
cat(sprintf("Rank based check (Wilcoxon rank sum, Yes versus No): W = %.0f, p = %s\n\n", mw$statistic, pf(mw$p.value)))

# ---- 9. Assumption checks ---------------------------------------------------
# (a) Paired t tests assume the DIFFERENCES are roughly normal (QQ plots and a
#     Shapiro Wilk test; with n near 25 the test has modest power, so read both).
#     (b) Mixed model: residuals versus fitted, residual QQ, and the QQ of the
#     random intercepts.
cat("---- 9. Assumption checks ----\n")
sw <- tibble(test = c("H1 Product_TV dwell (%)", "H2 Brand_Logo TTFF AOI (ms), both observed",
                      "H2b Brand_Logo TTFF AOI (ms), never fixated = 5000", "H3 Liking (1 to 7)"),
             n = c(res_h1$n, res_h2$n, res_h2b$n, res_h3$n),
             shapiro_p = round(c(res_h1$shapiro_p, res_h2$shapiro_p, res_h2b$shapiro_p, res_h3$shapiro_p), 3))
cat("Shapiro Wilk p for the paired differences (a low p flags non-normality; small n limits power):\n")
print(as.data.frame(sw), row.names = FALSE)
cat(sprintf("Shapiro Wilk p for the mixed model residuals: %.3f\n", shapiro.test(resid(mm))$p.value))
re_int <- ranef(mm)$respondent[, 1]
cat(sprintf("Shapiro Wilk p for the respondent random intercepts: %.3f\n", shapiro.test(re_int)$p.value))
cat("H3 differences are whole numbers (a 7 point scale), so they cannot be perfectly normal; the Wilcoxon result above is the companion check.\n")

png(file.path(fig_dir, "SIMULATED_assumption_checks.png"), width = 1400, height = 1000, res = 150)
par(mfrow = c(2, 3), mar = c(4, 4, 3, 1))
qqnorm(res_h1$dif, main = "H1 differences (dwell %): normal QQ", col = col_paint, pch = 16); qqline(res_h1$dif, col = "#444444")
qqnorm(res_h2$dif, main = "H2 differences (TTFF ms): normal QQ", col = col_paint, pch = 16); qqline(res_h2$dif, col = "#444444")
qqnorm(res_h3$dif, main = "H3 differences (liking): normal QQ", col = col_paint, pch = 16); qqline(res_h3$dif, col = "#444444")
plot(fitted(mm), resid(mm), pch = 16, col = "#1F386488", xlab = "Fitted dwell share (%)",
     ylab = "Residual", main = "Mixed model: residuals vs fitted"); abline(h = 0, col = col_accent)
qqnorm(resid(mm), main = "Mixed model: residual QQ", pch = 16, col = "#1F386488"); qqline(resid(mm), col = col_accent)
qqnorm(re_int, main = "Mixed model: respondent intercepts QQ", pch = 16, col = "#1F386488"); qqline(re_int, col = col_accent)
invisible(dev.off())
cat("saved figure: figures/SIMULATED_assumption_checks.png\n")
cat("Reading the plots: points near the line = roughly normal; a fan shape in\n",
    "residuals vs fitted = variance grows with the mean (consider a log or square\n",
    "root transform of dwell share, or a rank based test). Staircase points in the\n",
    "H3 plot are the whole number ratings.\n\n")

# ---- 10. Figures ------------------------------------------------------------
# One slope chart style for all three paired outcomes: a gray line per respondent
# connects the two commercials, and the mean with its 95 percent CI sits beside
# each commercial in the accent color so it never hides the individual points.
ci95 <- function(x) { x <- x[!is.na(x)]; qt(0.975, length(x) - 1) * sd(x) / sqrt(length(x)) }

slope_chart <- function(long, mean_df, ylab, title, subtitle, caption, scale_y, label_fmt = "%.1f", hollow = FALSE) {
  long <- long %>% mutate(pos = if_else(commercial == "Balls", 1, 2))
  mean_df <- mean_df %>% mutate(pos = if_else(commercial == "Balls", 1, 2),
                                xo = pos + if_else(pos == 1, -0.24, 0.24),
                                hj = if_else(pos == 1, 1.45, -0.45))
  ggplot() +
    geom_line(data = long %>% filter(linked), aes(x = pos, y = y, group = respondent),
              color = "#B8B8B8", linewidth = 0.5) +
    geom_point(data = long %>% filter(linked), aes(x = pos, y = y, color = commercial), size = 2.4, alpha = 0.85) +
    { if (hollow) geom_point(data = long %>% filter(!linked), aes(x = pos, y = y, color = commercial),
                             size = 3.8, shape = 1, stroke = 1.1) } +
    geom_errorbar(data = mean_df, aes(x = xo, ymin = mean - ci, ymax = mean + ci), width = 0.07,
                  linewidth = 0.9, color = col_accent) +
    geom_point(data = mean_df, aes(x = xo, y = mean), size = 4.2, color = col_accent) +
    geom_text(data = mean_df, aes(x = xo, y = mean, label = sprintf(paste0("M = ", label_fmt), mean), hjust = hj),
              size = 3.8, color = "#333333") +
    scale_color_manual(values = comm_colors, breaks = comm_levels, guide = "none") +
    scale_x_continuous(breaks = 1:2, labels = c("Balls\n(Commercial 1)", "Paint\n(Commercial 2)"),
                       limits = c(0.35, 2.65)) +
    scale_y +
    labs(title = title, subtitle = subtitle, x = NULL, y = ylab, caption = caption) +
    theme_ad() + theme(legend.position = "none")
}

# Figure 1: Product_TV Dwell time (%)
f1_long <- ptv_w %>% pivot_longer(c(Balls, Paint), names_to = "commercial", values_to = "y") %>%
  mutate(commercial = factor(commercial, levels = comm_levels), linked = TRUE)
f1_mean <- f1_long %>% group_by(commercial) %>% summarise(mean = mean(y), ci = ci95(y), .groups = "drop")
fig1 <- slope_chart(f1_long, f1_mean, "Dwell time (% of AOI active time)",
  "Share of looking time on the television set (Product_TV)",
  sprintf("Each line is one respondent; mean with 95%% CI in accent.\nPaired t(%d) = %.2f, %s, d_z = %.2f, 95%% CI [%.2f, %.2f]",
          as.integer(res_h1$df), res_h1$t, fp(res_h1$p), res_h1$dz, res_h1$dz_lo, res_h1$dz_hi),
  "SIMULATED teaching data (make_simulated_data.py). Not real viewers.\nDwell time (%) is relative to the time the AOI was active (14 s in Balls, 20 s in Paint).",
  scale_y = scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.06))))
save_fig(fig1, "SIMULATED_fig1_product_dwell_paired.png")

# Figure 2: Brand_Logo TTFF AOI (ms). Respondents with a value in both commercials
# are connected; respondents who never fixated the logo in one commercial appear as
# open circles with no line.
f2_long <- logo_w %>% pivot_longer(c(Balls, Paint), names_to = "commercial", values_to = "y") %>%
  filter(!is.na(y)) %>%
  mutate(commercial = factor(commercial, levels = comm_levels),
         linked = respondent %in% logo_w$respondent[!is.na(logo_w$Balls) & !is.na(logo_w$Paint)])
f2_mean <- f2_long %>% filter(linked) %>% group_by(commercial) %>%
  summarise(mean = mean(y), ci = ci95(y), .groups = "drop")
n_miss_b <- sum(is.na(logo_w$Balls)); n_miss_p <- sum(is.na(logo_w$Paint))
fig2 <- slope_chart(f2_long, f2_mean, "TTFF AOI (ms after the end card appears)",
  "Time to first fixation on the brand logo (Brand_Logo)",
  sprintf("Lines connect the %d respondents with a TTFF in both commercials; mean with 95%% CI in accent.\nPaired t(%d) = %.2f, %s, d_z = %.2f, 95%% CI [%.2f, %.2f]",
          res_h2$n, as.integer(res_h2$df), res_h2$t, fp(res_h2$p), res_h2$dz, res_h2$dz_lo, res_h2$dz_hi),
  sprintf("SIMULATED teaching data. Open circles: the respondent fixated the logo in one commercial only.\nNever fixated the logo (NA in the export): Balls %d, Paint %d of %d respondents.",
          n_miss_b, n_miss_p, nrow(logo_w)),
  scale_y = scale_y_continuous(limits = c(0, NA), expand = expansion(mult = c(0, 0.06))),
  label_fmt = "%.0f", hollow = TRUE)
save_fig(fig2, "SIMULATED_fig2_brand_logo_TTFF.png")

# Figure 3: Liking (1 to 7). Ratings are whole numbers, so a small vertical jitter
# (the same for a respondent's point and line end) keeps the lines from stacking.
set.seed(20268242)
f3_long <- survey_clean %>% select(respondent, Balls = liking_balls, Paint = liking_paint) %>%
  pivot_longer(c(Balls, Paint), names_to = "commercial", values_to = "rating") %>%
  mutate(commercial = factor(commercial, levels = comm_levels), y = rating + runif(n(), -0.18, 0.18), linked = TRUE)
f3_mean <- f3_long %>% group_by(commercial) %>% summarise(mean = mean(rating), ci = ci95(rating), .groups = "drop")
fig3 <- slope_chart(f3_long, f3_mean, "Liking (1 = dislike very much, 7 = like very much)",
  "Liking of each commercial after viewing it",
  sprintf("Each line is one respondent (points jittered slightly); mean with 95%% CI in accent.\nPaired t(%d) = %.2f, %s, d_z = %.2f, 95%% CI [%.2f, %.2f]",
          as.integer(res_h3$df), res_h3$t, fp(res_h3$p), res_h3$dz, res_h3$dz_lo, res_h3$dz_hi),
  sprintf("SIMULATED teaching data. %d of %d respondents preferred Balls, although Paint drew the larger share\nof looking time on the television set.",
          tab_pref["Balls"], sum(tab_pref)),
  scale_y = scale_y_continuous(breaks = 1:7, limits = c(0.8, 7.3)), label_fmt = "%.2f")
save_fig(fig3, "SIMULATED_fig3_liking.png")

# ---- Summary tables of the tests, for the results paragraph -----------------
row_of <- function(r) tibble(comparison = r$label, n = r$n, m_balls = r$m_b, m_paint = r$m_p,
                             mean_diff = r$diff, sd_diff = r$sd_diff, diff_ci_low = r$ci_lo, diff_ci_high = r$ci_hi,
                             t = r$t, df = r$df, p = r$p, dz = r$dz, dz_ci_low = r$dz_lo, dz_ci_high = r$dz_hi,
                             wilcoxon_V = r$V, wilcoxon_p = r$p_w)
tests <- bind_rows(
  row_of(res_h1) %>% mutate(comparison = "H1 Product_TV Dwell time (%)"),
  row_of(res_h2) %>% mutate(comparison = "H2 Brand_Logo TTFF AOI (ms), both observed"),
  row_of(res_h2b) %>% mutate(comparison = "H2b Brand_Logo TTFF AOI (ms), never fixated = 5000"),
  row_of(res_h3) %>% mutate(comparison = "H3 Liking (1 to 7)")) %>%
  mutate(across(where(is.numeric) & !any_of(c("p", "wilcoxon_p")), ~ round(.x, 6)),
         p = signif(p, 4), wilcoxon_p = signif(wilcoxon_p, 4))
cat("\n---- Summary of the paired tests (difference = Paint minus Balls) ----\n")
print(as.data.frame(tests %>% mutate(across(where(is.numeric), ~ round(.x, 3)))), row.names = FALSE)
write_csv(tests, "SIMULATED_test_results.csv")
cat("written: SIMULATED_test_results.csv\n")

models <- bind_rows(
  tibble(analysis = "Mixed model Product_TV dwell_pct", term = unname(term_labels[rownames(cf)]),
         estimate = cf$est, se = cf$se, df = cf$df, statistic = cf$t, p = cf$p, ci_low = cf$ci_lo, ci_high = cf$ci_hi),
  tibble(analysis = "Mixed model Product_TV dwell_pct", term = "ICC adjusted (fitted model)", estimate = icc_adj,
         se = NA_real_, df = NA_real_, statistic = NA_real_, p = NA_real_, ci_low = NA_real_, ci_high = NA_real_),
  tibble(analysis = "Mixed model Product_TV dwell_pct", term = "ICC unconditional (intercept only)", estimate = icc_null,
         se = NA_real_, df = NA_real_, statistic = NA_real_, p = NA_real_, ci_low = NA_real_, ci_high = NA_real_),
  tibble(analysis = "Mixed model Product_TV dwell_pct", term = "Simple order effect estimate ((Group A - Group B) / 2)",
         estimate = order_simple, se = NA_real_, df = NA_real_, statistic = NA_real_, p = NA_real_, ci_low = NA_real_, ci_high = NA_real_),
  tibble(analysis = "Point biserial: total Brand_Logo dwell (ms) with recall", term = "r_pb",
         estimate = unname(ct_rec$estimate), se = NA_real_, df = unname(ct_rec$parameter),
         statistic = unname(ct_rec$statistic), p = ct_rec$p.value,
         ci_low = ct_rec$conf.int[1], ci_high = ct_rec$conf.int[2]),
  tibble(analysis = "Exploratory: dwell difference with liking difference", term = "r",
         estimate = unname(ct_dis$estimate), se = NA_real_, df = unname(ct_dis$parameter),
         statistic = unname(ct_dis$statistic), p = ct_dis$p.value,
         ci_low = ct_dis$conf.int[1], ci_high = ct_dis$conf.int[2])) %>%
  mutate(across(where(is.numeric) & !any_of("p"), ~ round(.x, 6)), p = signif(p, 4))
write_csv(models, "SIMULATED_model_results.csv")
cat("written: SIMULATED_model_results.csv\n")
cat("\nDone. Reminder: every number above is SIMULATED for teaching.\n")
sink()
