# =============================================================================
# analysis.R
# Workshop: Mobile Eye Tracking Shelf Study, analysis session
# Martin's Family Clothing Consumer Behavior Research Laboratory, JSU
#
# SIMULATED DATA. Every number this script reads was generated by
# make_simulated_data.py (seed 20261037). No real shopper was recorded. The
# patterns mirror the iMotions "In-Store Shopper Report" (Sensodyne POSM versus
# no POSM, eye tracking glasses) only in direction and rough size.
#
# What the script does, in order:
#   0. Load packages and set paths and the figure theme
#   1. Read the simulated Individual AOI metrics export, the survey, and the log
#   2. Clean: apply the exclusion rule, treat never fixated AOIs correctly
#   3. Descriptive table by condition and AOI (mean, SD, n, respondent ratio)
#   4. Primary hypothesis: TTFF to Sensodyne_Products, POSM versus NoPOSM
#      (Welch t test, Cohen's d with 95 percent CI)
#   5. Secondary hypothesis: Dwell time (%) on Sensodyne_Products, same approach
#   6. Sensitivity check: Wilcoxon rank sum tests
#   7. Mixed effects model: dwell share across AOIs, respondent as random intercept
#   8. Assumption checks (plots saved to figures/)
#   9. Survey: purchase intent, brand recall, product chosen
#  10. Three report figures saved as PNG, 1400 px wide
#
# How to run (either way works):
#   a) In RStudio: open this file, set the working directory to the folder that
#      holds the CSV files (Session > Set Working Directory > To Source File
#      Location), then Source.
#   b) From a terminal, inside the data folder:  Rscript analysis.R
# The console output is also written to analysis_output.txt next to the data.
#
# Packages used: readr, dplyr, tidyr, ggplot2, lme4. Optional: lmerTest (gives
# p values for the mixed model), effectsize (noncentral t confidence interval
# for Cohen's d). If a package is missing, run once in the console:
#   install.packages(c("readr", "dplyr", "tidyr", "ggplot2", "lme4",
#                      "lmerTest", "effectsize"))
# =============================================================================

# ---- 0. Setup ---------------------------------------------------------------
suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(lme4)
})
has_lmerTest   <- requireNamespace("lmerTest",   quietly = TRUE)
has_effectsize <- requireNamespace("effectsize", quietly = TRUE)

# Find the folder that holds this script, so the CSV paths work in RStudio and
# from Rscript alike. Falls back to the current working directory.
script_dir <- tryCatch({
  args <- commandArgs(trailingOnly = FALSE)
  f <- sub("^--file=", "", args[grep("^--file=", args)])
  if (length(f) == 1) dirname(normalizePath(f)) else getwd()
}, error = function(e) getwd())
setwd(script_dir)
fig_dir <- file.path(script_dir, "figures")
dir.create(fig_dir, showWarnings = FALSE)

# Save the console output next to the data. split = TRUE keeps it on screen too.
output_file <- file.path(script_dir, "analysis_output.txt")
sink(output_file, split = TRUE)
cat("SIMULATED shelf study analysis, run on", format(Sys.time(), "%Y-%m-%d %H:%M"), "\n")
cat("R", R.version$major, ".", R.version$minor, "; lme4 ", as.character(packageVersion("lme4")),
    "; lmerTest available: ", has_lmerTest, "; effectsize available: ", has_effectsize, "\n\n", sep = "")

# Palette: navy (POSM), gray (NoPOSM), one accent for emphasis. Legends and direct
# labels carry the identity as well, so color is never the only cue.
col_posm   <- "#1F3864"
col_noposm <- "#8C8C8C"
col_accent <- "#A6561A"
cond_colors <- c(POSM = col_posm, NoPOSM = col_noposm)
cond_levels <- c("NoPOSM", "POSM")   # control first, treatment second

theme_shelf <- function(base_size = 13) {
  theme_minimal(base_size = base_size) +
    theme(panel.grid.minor = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.major.y = element_line(color = "#E3E3E3", linewidth = 0.4),
          axis.line.x = element_line(color = "#B0B0B0", linewidth = 0.4),
          plot.title = element_text(face = "bold", size = base_size + 2),
          plot.subtitle = element_text(color = "#555555"),
          plot.caption = element_text(color = "#777777", size = base_size - 3, hjust = 0),
          legend.position = "top",
          legend.title = element_blank(),
          plot.background = element_rect(fill = "white", color = NA))
}
save_fig <- function(plot, name, height_px = 900) {
  # 1400 px wide at 150 dpi = 9.33 in wide
  ggsave(file.path(fig_dir, name), plot, width = 1400 / 150, height = height_px / 150,
         dpi = 150, bg = "white")
  cat("saved figure:", file.path("figures", name), "\n")
}

# ---- 1. Read the files ------------------------------------------------------
# Line 1 of every file is a "# SIMULATED" comment, so comment = "#" skips it.
# iMotions writes NA when a metric cannot be calculated (for example, the
# respondent never fixated the AOI), so na = "NA".
aoi_raw <- read_csv("SIMULATED_shelf_study_AOI_metrics.csv", comment = "#",
                    na = c("NA", ""), show_col_types = FALSE)
survey  <- read_csv("SIMULATED_shelf_study_survey.csv",  comment = "#", show_col_types = FALSE)
session <- read_csv("SIMULATED_shelf_study_session_log.csv", comment = "#", show_col_types = FALSE)

cat("---- 1. Files read ----\n")
cat("AOI metrics rows:", nrow(aoi_raw), " respondents:", n_distinct(aoi_raw$`Respondent Name`),
    " AOIs:", paste(unique(aoi_raw$`AOI Name`), collapse = ", "), "\n")
cat("Survey rows:", nrow(survey), "  Session log rows:", nrow(session), "\n\n")

# Rename the iMotions column names to short R friendly names. Keep this block as
# the one place where the mapping from export header to variable lives.
aoi <- aoi_raw %>%
  rename(respondent   = `Respondent Name`,
         condition    = Group,
         sex          = Gender,
         age_band     = Age,
         session_date = `Session Date`,
         stimulus     = Stimulus,
         aoi          = `AOI Name`,
         stim_dur_ms  = `Stimulus duration`,
         valid_pct    = `Valid data`,
         hit_time_ms  = `Gaze Hit time parent (ms)`,
         fix_count    = `Fixation count`,
         revisits     = `Revisit count`,
         ttff_ms      = `TTFF parent (ms)`,
         ttff_max_ms  = `TTFF max. (ms)`,
         dwell_ms     = `Dwell time (ms)`,
         dwell_pct    = `Dwell time (%)`,
         fix_dur_ms   = `Fixation duration (ms)`) %>%
  mutate(condition = factor(condition, levels = cond_levels))

# ---- 2. Clean ---------------------------------------------------------------
# Exclusion rule, fixed before data collection: Valid data below 70 percent.
# Valid data is an Information metric (percentage of collected and interpolated
# samples); on glasses data it is the first screen for gaze mapping coverage.
excluded <- aoi %>% filter(valid_pct < 70) %>% distinct(respondent, condition, valid_pct)
cat("---- 2. Cleaning ----\n")
cat("Excluded (Valid data < 70 percent):\n"); print(as.data.frame(excluded))
cat("Session log says for these respondents:\n")
print(as.data.frame(session %>% filter(`Respondent Name` %in% excluded$respondent) %>%
                      select(`Respondent Name`, `Data complete`, `Decision note`)))

aoi_clean <- aoi %>%
  filter(valid_pct >= 70) %>%
  mutate(
    fixated   = !is.na(ttff_ms),                 # TRUE when at least one fixation hit the AOI
    # A never fixated AOI has no TTFF: it stays NA ("not observed"). It does have a
    # dwell time, which is zero. The same logic applies to the fixation count.
    dwell_ms  = if_else(is.na(dwell_ms), 0, dwell_ms),
    dwell_pct = if_else(is.na(dwell_pct), 0, dwell_pct),
    fix_count = if_else(is.na(fix_count), 0L, as.integer(fix_count)),
    revisits  = if_else(is.na(revisits), 0L, as.integer(revisits)),
    ttff_s    = ttff_ms / 1000,                  # seconds read more easily than ms
    dwell_s   = dwell_ms / 1000)

n_by_cond <- aoi_clean %>% distinct(respondent, condition) %>% count(condition)
cat("\nRespondents kept per condition:\n"); print(as.data.frame(n_by_cond))
cat("Rows with no fixation on the AOI (TTFF not observed, dwell set to 0):",
    sum(!aoi_clean$fixated), "of", nrow(aoi_clean), "\n\n")

# ---- 3. Descriptive table by condition and AOI ------------------------------
# TTFF: mean and SD over respondents who fixated the AOI (n_ttff).
# Dwell share and fixation count: all kept respondents (zeros included).
# Respondent ratio (%): share of respondents with at least one fixation, which
# is the fixation based "Respondent ratio (%)" metric in the iMotions table.
desc <- aoi_clean %>%
  group_by(aoi, condition) %>%
  summarise(n = n(),
            resp_ratio_pct = round(100 * mean(fixated), 1),
            n_ttff   = sum(fixated),
            ttff_mean_s = mean(ttff_s, na.rm = TRUE),
            ttff_sd_s   = sd(ttff_s, na.rm = TRUE),
            dwell_mean_pct = mean(dwell_pct),
            dwell_sd_pct   = sd(dwell_pct),
            dwell_mean_s   = mean(dwell_s),
            fix_mean = mean(fix_count),
            fix_sd   = sd(fix_count),
            .groups = "drop") %>%
  mutate(across(where(is.double), ~ round(.x, 2))) %>%
  arrange(aoi, condition)
cat("---- 3. Descriptive table by AOI and condition ----\n")
print(as.data.frame(desc), row.names = FALSE)
write_csv(desc, "SIMULATED_descriptives_by_condition_AOI.csv")
cat("written: SIMULATED_descriptives_by_condition_AOI.csv\n\n")

# Time on competitor products per respondent (sum of the two competitor AOIs),
# the comparison the 2020 report headlined (almost 25 percent less with POSM).
comp <- aoi_clean %>%
  filter(aoi %in% c("Competitor_A", "Competitor_B")) %>%
  group_by(respondent, condition) %>%
  summarise(comp_dwell_s = sum(dwell_s), .groups = "drop")
cat("Time on competitor products (s), mean by condition:\n")
print(as.data.frame(comp %>% group_by(condition) %>%
                      summarise(mean_s = round(mean(comp_dwell_s), 1), sd_s = round(sd(comp_dwell_s), 1), n = n())))
cat("\n")

# ---- Helper: Welch t test plus Cohen's d with a 95 percent CI ---------------
# Cohen's d uses the pooled SD. The CI comes from effectsize::cohens_d (noncentral
# t method) when the package is installed; otherwise from the large sample
# approximation SE(d) = sqrt((n1 + n2) / (n1 * n2) + d^2 / (2 (n1 + n2))).
report_two_groups <- function(x_treat, x_ctrl, label, unit) {
  x_treat <- x_treat[!is.na(x_treat)]; x_ctrl <- x_ctrl[!is.na(x_ctrl)]
  n1 <- length(x_treat); n2 <- length(x_ctrl)
  tt <- t.test(x_treat, x_ctrl, var.equal = FALSE)      # Welch: unequal variances allowed
  sp <- sqrt(((n1 - 1) * var(x_treat) + (n2 - 1) * var(x_ctrl)) / (n1 + n2 - 2))
  d  <- (mean(x_treat) - mean(x_ctrl)) / sp
  if (has_effectsize) {
    es <- effectsize::cohens_d(x_treat, x_ctrl, pooled_sd = TRUE, ci = 0.95)
    d_lo <- es$CI_low; d_hi <- es$CI_high; ci_method <- "noncentral t (effectsize)"
  } else {
    se_d <- sqrt((n1 + n2) / (n1 * n2) + d^2 / (2 * (n1 + n2)))
    d_lo <- d - 1.96 * se_d; d_hi <- d + 1.96 * se_d; ci_method <- "large sample approximation"
  }
  cat(sprintf("%s\n", label))
  cat(sprintf("  POSM:   M = %.2f %s, SD = %.2f, n = %d\n", mean(x_treat), unit, sd(x_treat), n1))
  cat(sprintf("  NoPOSM: M = %.2f %s, SD = %.2f, n = %d\n", mean(x_ctrl),  unit, sd(x_ctrl),  n2))
  cat(sprintf("  Difference (POSM minus NoPOSM) = %.2f %s, 95%% CI [%.2f, %.2f]\n",
              mean(x_treat) - mean(x_ctrl), unit, tt$conf.int[1], tt$conf.int[2]))
  cat(sprintf("  Welch t(%.1f) = %.2f, p = %.4f\n", tt$parameter, tt$statistic, tt$p.value))
  cat(sprintf("  Cohen's d = %.2f, 95%% CI [%.2f, %.2f]  (%s)\n\n", d, d_lo, d_hi, ci_method))
  invisible(list(t = tt, d = d, d_lo = d_lo, d_hi = d_hi, n1 = n1, n2 = n2))
}

# ---- 4. Primary hypothesis: TTFF to Sensodyne_Products ---------------------
# H1: POSM shortens the time to first fixation on Sensodyne products.
# Only respondents who fixated the AOI have a TTFF, so n is below the group size.
cat("---- 4. Primary test: TTFF parent (s) to Sensodyne_Products ----\n")
sens <- aoi_clean %>% filter(aoi == "Sensodyne_Products")
res_ttff <- report_two_groups(sens$ttff_s[sens$condition == "POSM"],
                              sens$ttff_s[sens$condition == "NoPOSM"],
                              "TTFF to Sensodyne_Products (respondents who fixated it)", "s")

# A second look that keeps the non fixators: TTFF max. (ms) assigns the parent
# duration when the AOI was never fixated (iMotions definition). It answers a
# slightly different question (how long until the brand was noticed, counting
# shoppers who never noticed it as the full exposure).
res_ttff_max <- report_two_groups(sens$ttff_max_ms[sens$condition == "POSM"] / 1000,
                                  sens$ttff_max_ms[sens$condition == "NoPOSM"] / 1000,
                                  "TTFF max. (s) to Sensodyne_Products (non fixators = full exposure)", "s")
if (all(sens$fixated)) {
  cat("Note: every kept respondent fixated Sensodyne_Products in this sample, so TTFF max.\n",
      "equals TTFF parent and the two analyses coincide. With real data they usually differ.\n\n")
}

# ---- 5. Secondary hypothesis: dwell time share on Sensodyne_Products -------
cat("---- 5. Secondary test: Dwell time (%) on Sensodyne_Products ----\n")
res_dwell <- report_two_groups(sens$dwell_pct[sens$condition == "POSM"],
                               sens$dwell_pct[sens$condition == "NoPOSM"],
                               "Dwell time (%) on Sensodyne_Products (all kept respondents)", "%")

# Competitor time, the 2020 report's headline comparison
cat("---- 5b. Time on competitor products (s) ----\n")
res_comp <- report_two_groups(comp$comp_dwell_s[comp$condition == "POSM"],
                              comp$comp_dwell_s[comp$condition == "NoPOSM"],
                              "Dwell time (s) on Competitor_A plus Competitor_B", "s")

# ---- 6. Sensitivity check: Wilcoxon rank sum (Mann Whitney) ----------------
# TTFF is right skewed and the groups are small, so a rank based test is a
# sensible check. If it agrees with the t test, the conclusion is robust.
cat("---- 6. Sensitivity: Wilcoxon rank sum tests ----\n")
w1 <- wilcox.test(ttff_s ~ condition, data = sens, exact = FALSE)
w2 <- wilcox.test(dwell_pct ~ condition, data = sens, exact = FALSE)
cat(sprintf("TTFF Sensodyne_Products:  W = %.0f, p = %.4f\n", w1$statistic, w1$p.value))
cat(sprintf("Dwell %% Sensodyne_Products: W = %.0f, p = %.4f\n\n", w2$statistic, w2$p.value))

# ---- 7. Mixed effects model: dwell share across AOIs -----------------------
# Each respondent contributes one dwell share per AOI, so the rows are not
# independent. A random intercept for respondent absorbs the shopper level
# tendency to look longer or shorter overall. Sensodyne_POSM_Wing exists only on
# the POSM shelf, so it is left out of the AOI by condition interaction model.
# Dwell time (%) is the response; the fixed effects are AOI, condition, and
# their interaction. The interaction says: does the POSM effect differ by AOI?
cat("---- 7. Mixed effects model: Dwell time (%) ~ AOI * condition + (1 | respondent) ----\n")
mm_data <- aoi_clean %>%
  filter(aoi != "Sensodyne_POSM_Wing") %>%
  mutate(aoi = factor(aoi, levels = c("Shelf_Other", "Sensodyne_Products", "Competitor_A",
                                      "Competitor_B", "Price_Tags")))
if (has_lmerTest) {
  mm <- lmerTest::lmer(dwell_pct ~ aoi * condition + (1 | respondent), data = mm_data, REML = TRUE)
  print(summary(mm, correlation = FALSE))
  cat("\nType III tests (Satterthwaite degrees of freedom):\n")
  print(anova(mm, type = 3))
} else {
  mm <- lme4::lmer(dwell_pct ~ aoi * condition + (1 | respondent), data = mm_data, REML = TRUE)
  print(summary(mm, correlation = FALSE))
  cat("\nlmerTest is not installed, so no p values are printed. A |t| above about 2\n",
      "is the usual rough guide; install lmerTest for Satterthwaite p values.\n")
}
# Interpretation aid: model based means by AOI and condition
cat("\nModel based mean dwell share (%) by AOI and condition (fixed effects only):\n")
grid <- expand.grid(aoi = levels(mm_data$aoi), condition = factor(cond_levels, levels = cond_levels))
grid$fit <- predict(mm, newdata = grid, re.form = NA)
print(as.data.frame(grid %>% pivot_wider(names_from = condition, values_from = fit) %>%
                      mutate(across(where(is.numeric), ~ round(.x, 1)))), row.names = FALSE)
cat("\n")

# ---- 8. Assumption checks ---------------------------------------------------
# (a) t tests: approximate normality within each group (QQ plots) and similar
#     spread (Welch does not require equal variances, but large differences
#     are worth noticing). (b) Mixed model: residuals versus fitted and a
#     residual QQ plot; random intercepts roughly normal.
cat("---- 8. Assumption checks ----\n")
cat("Variance ratio (larger / smaller) for TTFF:",
    round(max(tapply(sens$ttff_s, sens$condition, var, na.rm = TRUE)) /
          min(tapply(sens$ttff_s, sens$condition, var, na.rm = TRUE)), 2), "\n")
sw <- sens %>% filter(!is.na(ttff_s)) %>% group_by(condition) %>%
  summarise(shapiro_p = round(shapiro.test(ttff_s)$p.value, 3), .groups = "drop")
cat("Shapiro Wilk p for TTFF within condition (a low p flags skew; small n limits power):\n")
print(as.data.frame(sw))

png(file.path(fig_dir, "SIMULATED_assumption_checks.png"), width = 1400, height = 1000, res = 150)
par(mfrow = c(2, 2), mar = c(4, 4, 3, 1))
qqnorm(sens$ttff_s[sens$condition == "NoPOSM"], main = "TTFF, NoPOSM: normal QQ", col = col_noposm, pch = 16)
qqline(sens$ttff_s[sens$condition == "NoPOSM"], col = "#444444")
qqnorm(sens$ttff_s[sens$condition == "POSM"], main = "TTFF, POSM: normal QQ", col = col_posm, pch = 16)
qqline(sens$ttff_s[sens$condition == "POSM"], col = "#444444")
plot(fitted(mm), resid(mm), pch = 16, col = "#1F386488", xlab = "Fitted dwell share (%)",
     ylab = "Residual", main = "Mixed model: residuals vs fitted"); abline(h = 0, col = col_accent)
qqnorm(resid(mm), main = "Mixed model: residual QQ", pch = 16, col = "#1F386488"); qqline(resid(mm), col = col_accent)
invisible(dev.off())
cat("saved figure: figures/SIMULATED_assumption_checks.png\n")
cat("Reading the plots: points near the line = roughly normal; a fan shape in\n",
    "residuals vs fitted = variance grows with the mean (consider a log or square\n",
    "root transform of dwell share, or a rank based test).\n\n")

# ---- 9. Survey --------------------------------------------------------------
cat("---- 9. Survey (collected after the glasses came off) ----\n")
survey_clean <- survey %>%
  rename(respondent = `Respondent Name`, condition = Group,
         purchase_intent = Purchase_intent_Sensodyne_1to7,
         brand_recall = Brand_recall_Sensodyne, product_chosen = Product_chosen) %>%
  filter(!respondent %in% excluded$respondent) %>%
  mutate(condition = factor(condition, levels = cond_levels))
res_pi <- report_two_groups(survey_clean$purchase_intent[survey_clean$condition == "POSM"],
                            survey_clean$purchase_intent[survey_clean$condition == "NoPOSM"],
                            "Purchase intent for Sensodyne (1 to 7)", "points")
cat("Brand recall of Sensodyne by condition:\n")
tab_recall <- table(survey_clean$condition, survey_clean$brand_recall)
print(tab_recall)
ft <- fisher.test(tab_recall)
cat(sprintf("Fisher exact test p = %.3f (small counts, so Fisher rather than chi square)\n\n", ft$p.value))
cat("Product chosen by condition:\n")
tab_choice <- table(survey_clean$condition, survey_clean$product_chosen)
print(tab_choice)
cat(sprintf("Fisher exact test p = %.3f\n\n", fisher.test(tab_choice)$p.value))
# Does attention relate to self report? Join dwell share on Sensodyne to the survey.
link <- sens %>% select(respondent, condition, dwell_pct, ttff_s) %>%
  inner_join(survey_clean, by = c("respondent", "condition"))
ct <- cor.test(link$dwell_pct, link$purchase_intent)
cat(sprintf("Correlation, Sensodyne dwell share with purchase intent: r = %.2f, 95%% CI [%.2f, %.2f], p = %.4f\n\n",
            ct$estimate, ct$conf.int[1], ct$conf.int[2], ct$p.value))

# ---- 10. Figures ------------------------------------------------------------
# Figure 1: bar chart of mean TTFF by condition with 95 percent CIs and the
# individual respondents as small points (so the spread is visible).
ci95 <- function(x) { x <- x[!is.na(x)]; qt(0.975, length(x) - 1) * sd(x) / sqrt(length(x)) }
f1_sum <- sens %>% filter(!is.na(ttff_s)) %>% group_by(condition) %>%
  summarise(mean = mean(ttff_s), ci = ci95(ttff_s), n = n(), .groups = "drop")
fig1 <- ggplot(f1_sum, aes(x = condition, y = mean, fill = condition)) +
  geom_col(width = 0.55) +
  geom_errorbar(aes(ymin = mean - ci, ymax = mean + ci), width = 0.12, linewidth = 0.7, color = col_accent) +
  geom_jitter(data = sens %>% filter(!is.na(ttff_s)), aes(x = condition, y = ttff_s),
              inherit.aes = FALSE, width = 0.10, height = 0, size = 2.0, shape = 21,
              fill = "white", color = "#333333", alpha = 0.8) +
  geom_text(aes(label = sprintf("M = %.2f s\nn = %d", mean, n), y = 0.25), color = "white", size = 3.8, lineheight = 0.9) +
  scale_fill_manual(values = cond_colors, breaks = cond_levels) +
  scale_x_discrete(labels = c(NoPOSM = "No POSM shelf", POSM = "POSM shelf")) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.08))) +
  labs(title = "Time to first fixation on Sensodyne products",
       subtitle = sprintf("Mean with 95%% CI; points are respondents who fixated the AOI. Welch t(%.1f) = %.2f, p = %.3f, d = %.2f",
                          res_ttff$t$parameter, res_ttff$t$statistic, res_ttff$t$p.value, res_ttff$d),
       x = NULL, y = "TTFF parent (s)",
       caption = "SIMULATED teaching data (make_simulated_data.py). Not real shoppers.") +
  theme_shelf() + theme(legend.position = "none")
save_fig(fig1, "SIMULATED_fig1_TTFF_by_condition.png")

# Figure 2: dot and interval plot of mean dwell share by AOI and condition.
f2_sum <- aoi_clean %>% group_by(aoi, condition) %>%
  summarise(mean = mean(dwell_pct), ci = ci95(dwell_pct), n = n(), .groups = "drop") %>%
  mutate(aoi = factor(aoi, levels = rev(c("Sensodyne_Products", "Sensodyne_POSM_Wing", "Competitor_A",
                                          "Competitor_B", "Price_Tags", "Shelf_Other"))))
fig2 <- ggplot(f2_sum, aes(x = mean, y = aoi, color = condition)) +
  geom_errorbarh(aes(xmin = mean - ci, xmax = mean + ci), height = 0, linewidth = 0.8,
                 position = position_dodge(width = 0.6)) +
  geom_point(size = 3.2, position = position_dodge(width = 0.6)) +
  # value label just past the right end of each interval, so nothing overlaps
  geom_text(aes(x = mean + ci, label = sprintf("%.1f", mean), group = condition),
            position = position_dodge(width = 0.6), hjust = -0.25, size = 3.3,
            show.legend = FALSE, color = "#333333") +
  scale_color_manual(values = cond_colors, breaks = cond_levels,
                     labels = c(NoPOSM = "No POSM shelf", POSM = "POSM shelf")) +
  scale_x_continuous(expand = expansion(mult = c(0.02, 0.08))) +
  labs(title = "Dwell time share by AOI and shelf condition",
       subtitle = "Mean Dwell time (%) of the shelf exposure with 95% CI; never fixated AOIs count as 0",
       x = "Dwell time (% of shelf exposure)", y = NULL,
       caption = "SIMULATED teaching data. Sensodyne_POSM_Wing exists only on the POSM shelf.") +
  theme_shelf() + theme(panel.grid.major.y = element_blank(), panel.grid.major.x = element_line(color = "#E3E3E3", linewidth = 0.4))
save_fig(fig2, "SIMULATED_fig2_dwell_share_by_AOI.png", height_px = 950)

# Figure 3: purchase intent by condition (mean with 95 percent CI and the
# individual ratings), with the response counts as a second panel.
f3_sum <- survey_clean %>% group_by(condition) %>%
  summarise(mean = mean(purchase_intent), ci = ci95(purchase_intent), n = n(), .groups = "drop")
fig3 <- ggplot() +
  geom_jitter(data = survey_clean, aes(x = condition, y = purchase_intent, color = condition),
              width = 0.12, height = 0.08, size = 2.2, alpha = 0.55) +
  geom_errorbar(data = f3_sum, aes(x = condition, ymin = mean - ci, ymax = mean + ci),
                width = 0.15, linewidth = 0.8, color = col_accent) +
  geom_point(data = f3_sum, aes(x = condition, y = mean), size = 4, color = col_accent) +
  geom_text(data = f3_sum, aes(x = condition, y = mean, label = sprintf("M = %.2f", mean)),
            hjust = -0.35, size = 3.8, color = "#333333") +
  scale_color_manual(values = cond_colors, breaks = cond_levels,
                     labels = c(NoPOSM = "No POSM shelf", POSM = "POSM shelf")) +
  scale_x_discrete(labels = c(NoPOSM = "No POSM shelf", POSM = "POSM shelf")) +
  scale_y_continuous(breaks = 1:7, limits = c(0.8, 7.2)) +
  labs(title = "Stated purchase intent for Sensodyne after shopping the shelf",
       subtitle = sprintf("1 = definitely would not buy, 7 = definitely would buy. Mean with 95%% CI in accent, ratings as points.\nWelch t(%.1f) = %.2f, p = %.3f, d = %.2f",
                          res_pi$t$parameter, res_pi$t$statistic, res_pi$t$p.value, res_pi$d),
       x = NULL, y = "Purchase intent (1 to 7)",
       caption = "SIMULATED teaching data. Survey answered after the glasses were removed.") +
  theme_shelf() + theme(legend.position = "none")
save_fig(fig3, "SIMULATED_fig3_purchase_intent.png")

# ---- Summary table of the tests, for the results paragraph ------------------
tests <- tibble(
  comparison = c("TTFF Sensodyne_Products (s)", "TTFF max. Sensodyne_Products (s)",
                 "Dwell time (%) Sensodyne_Products", "Competitor dwell (s)", "Purchase intent (1 to 7)"),
  m_posm   = c(res_ttff$t$estimate[1], res_ttff_max$t$estimate[1], res_dwell$t$estimate[1], res_comp$t$estimate[1], res_pi$t$estimate[1]),
  m_noposm = c(res_ttff$t$estimate[2], res_ttff_max$t$estimate[2], res_dwell$t$estimate[2], res_comp$t$estimate[2], res_pi$t$estimate[2]),
  t  = c(res_ttff$t$statistic, res_ttff_max$t$statistic, res_dwell$t$statistic, res_comp$t$statistic, res_pi$t$statistic),
  df = c(res_ttff$t$parameter, res_ttff_max$t$parameter, res_dwell$t$parameter, res_comp$t$parameter, res_pi$t$parameter),
  p  = c(res_ttff$t$p.value, res_ttff_max$t$p.value, res_dwell$t$p.value, res_comp$t$p.value, res_pi$t$p.value),
  d  = c(res_ttff$d, res_ttff_max$d, res_dwell$d, res_comp$d, res_pi$d),
  d_ci_low  = c(res_ttff$d_lo, res_ttff_max$d_lo, res_dwell$d_lo, res_comp$d_lo, res_pi$d_lo),
  d_ci_high = c(res_ttff$d_hi, res_ttff_max$d_hi, res_dwell$d_hi, res_comp$d_hi, res_pi$d_hi)) %>%
  mutate(across(where(is.numeric), ~ round(.x, 3)))
cat("\n---- Summary of the two group tests ----\n")
print(as.data.frame(tests), row.names = FALSE)
write_csv(tests, "SIMULATED_test_results.csv")
cat("written: SIMULATED_test_results.csv\n")
cat("\nDone. Reminder: every number above is SIMULATED for teaching.\n")
sink()
