#!/usr/bin/env python3
"""
make_excel_workbook.py
Builds SIMULATED_shelf_study_analysis.xlsx from the three SIMULATED CSV files with
openpyxl. The workbook mirrors analysis.R for students who work in Excel:

  README    what the workbook is, and that every number is SIMULATED
  Data      the Individual AOI metrics export as imported (NA kept as text), plus
            four helper columns (Keep, TTFF_s, Dwell_pct_clean, Fixated)
  Summary   pivot style table by AOI and condition built with COUNTIFS,
            AVERAGEIFS, and STDEV.S array formulas (the hand built PivotTable)
  Sensodyne the Sensodyne_Products rows for kept respondents, sorted by condition,
            which is what a student gets from AutoFilter, copy, paste; the t test
            and Cohen's d are computed on this sheet with exact formulas shown
  Survey    the survey file joined to the Sensodyne dwell share, with the purchase
            intent T.TEST and a CORREL
  Check     the values analysis.R produced, so students can confirm their formulas

All formulas are ordinary Excel formulas. The three STDEV.S(IF(...)) formulas on
the Summary sheet are array formulas; Excel 365 evaluates them with Enter, older
Excel needs Ctrl+Shift+Enter (openpyxl writes them as array formulas already).

Run: python3 make_excel_workbook.py   (after make_simulated_data.py and analysis.R)
"""

import csv
import os

from openpyxl import Workbook
from openpyxl.chart import BarChart, Reference
from openpyxl.chart.error_bar import ErrorBars
from openpyxl.chart.data_source import NumDataSource, NumRef
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter
from openpyxl.worksheet.formula import ArrayFormula

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "SIMULATED_shelf_study_analysis.xlsx")

NAVY = "1F3864"
GRAY = "8C8C8C"
ACCENT = "A6561A"
LIGHT = "F2F2F2"

hdr_font = Font(bold=True, color="FFFFFF")
hdr_fill = PatternFill("solid", fgColor=NAVY)
sub_fill = PatternFill("solid", fgColor=LIGHT)
bold = Font(bold=True)
note_font = Font(italic=True, color="555555")
thin = Side(style="thin", color="BFBFBF")
box = Border(top=thin, bottom=thin, left=thin, right=thin)


def read_csv(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as fh:
        lines = [ln for ln in fh if not ln.startswith("#")]
    rows = list(csv.reader(lines))
    return rows[0], rows[1:]


def to_cell(v):
    """Numbers become numbers; NA stays the text NA (as iMotions writes it)."""
    if v == "NA" or v == "":
        return v
    try:
        f = float(v)
        return int(f) if f.is_integer() and "." not in v else f
    except ValueError:
        return v


def style_header(ws, row=1, ncol=None):
    ncol = ncol or ws.max_column
    for c in range(1, ncol + 1):
        cell = ws.cell(row=row, column=c)
        cell.font = hdr_font
        cell.fill = hdr_fill
        cell.alignment = Alignment(wrap_text=True, vertical="center")
        cell.border = box


def autowidth(ws, min_w=8, max_w=44):
    widths = {}
    for row in ws.iter_rows():
        for cell in row:
            if cell.value is None:
                continue
            L = len(str(cell.value)) if not str(cell.value).startswith("=") else 12
            widths[cell.column_letter] = max(widths.get(cell.column_letter, 0), L)
    for col, w in widths.items():
        ws.column_dimensions[col].width = max(min_w, min(max_w, w + 2))


wb = Workbook()

# ---------------------------------------------------------------- README
ws = wb.active
ws.title = "README"
readme = [
    "SIMULATED shelf study workbook (teaching material)",
    "",
    "Every number in this workbook is SIMULATED. It was generated by make_simulated_data.py",
    "(seed 20261037) to mirror the iMotions In-Store Shopper Report (Sensodyne POSM versus",
    "no POSM, eye tracking glasses) in direction and rough size only. No real shopper was recorded.",
    "",
    "Sheets:",
    "  Data       Individual AOI metrics export as imported. NA is kept as text, as iMotions writes it.",
    "             Helper columns Z to AC: Keep (Valid data >= 70), TTFF_s, Dwell_pct_clean, Fixated.",
    "  Summary    Mean, SD, n by AOI and condition, built with COUNTIFS, AVERAGEIFS, STDEV.S(IF(...)).",
    "  Sensodyne  The Sensodyne_Products rows for kept respondents, sorted by condition.",
    "             Welch t test (T.TEST type 3), hand computed t, Cohen's d, 95 percent CI.",
    "  Survey     Purchase intent, brand recall, product chosen; T.TEST and CORREL with attention.",
    "  Check      Values from analysis.R to confirm your formulas.",
    "",
    "Column names follow the iMotions AOI Metrics help article. Where the same metric name exists",
    "as a gaze based and a fixation based metric, the gaze based one is prefixed 'Gaze'.",
    "Exclusion rule, fixed before data collection: Valid data below 70 percent (respondent P17).",
    "Never fixated AOI: TTFF is not observed (left out of TTFF statistics); dwell time counts as 0.",
    "",
    "Companion files: analysis_excel_walkthrough.md (step by step), analysis.R (same analysis in R).",
]
for i, line in enumerate(readme, start=1):
    ws.cell(row=i, column=1, value=line)
ws["A1"].font = Font(bold=True, size=14, color=NAVY)
ws.column_dimensions["A"].width = 110

# ---------------------------------------------------------------- Data
header, rows = read_csv("SIMULATED_shelf_study_AOI_metrics.csv")
ws = wb.create_sheet("Data")
helper = ["Keep", "TTFF_s", "Dwell_pct_clean", "Fixated"]
ws.append(header + helper)
style_header(ws)
n_data = len(rows)
first, last = 2, n_data + 1
for i, r in enumerate(rows, start=first):
    ws.append([to_cell(v) for v in r])
    # Helper formulas. Column letters: L = Valid data, T = TTFF parent (ms), W = Dwell time (%)
    ws.cell(row=i, column=26, value=f'=IF(L{i}>=70,"Yes","No")')          # Z  Keep
    ws.cell(row=i, column=27, value=f'=IF(ISNUMBER(T{i}),T{i}/1000,"")')  # AA TTFF_s
    ws.cell(row=i, column=28, value=f"=IF(ISNUMBER(W{i}),W{i},0)")        # AB Dwell_pct_clean
    ws.cell(row=i, column=29, value=f"=IF(ISNUMBER(T{i}),1,0)")           # AC Fixated
ws.freeze_panes = "C2"
ws.auto_filter.ref = f"A1:{get_column_letter(len(header) + len(helper))}{last}"
autowidth(ws, max_w=24)
for col in ("Z", "AA", "AB", "AC"):
    ws[f"{col}1"].fill = PatternFill("solid", fgColor=ACCENT)

# Named ranges make the formulas readable in the walkthrough
rng = lambda col: f"Data!${col}${first}:${col}${last}"
R_GROUP, R_AOI, R_KEEP, R_TTFF, R_DWELL, R_FIX, R_FIXCOUNT = (
    rng("E"), rng("H"), rng("Z"), rng("AA"), rng("AB"), rng("AC"), rng("R"))

# ---------------------------------------------------------------- Summary
ws = wb.create_sheet("Summary")
ws["A1"] = "Descriptive table by AOI and condition (kept respondents only). SIMULATED data."
ws["A1"].font = Font(bold=True, size=12, color=NAVY)
ws["A2"] = ("n = kept respondents with a row for the AOI; Respondent ratio = percent who fixated the AOI; "
            "TTFF statistics use fixators only; dwell statistics count never fixated AOIs as 0.")
ws["A2"].font = note_font
cols = ["AOI", "Condition", "n", "Respondent ratio (%)", "n with TTFF", "TTFF mean (s)", "TTFF SD (s)",
        "Dwell time mean (%)", "Dwell time SD (%)", "Fixation count mean"]
ws.append([]); ws.append(cols)
style_header(ws, row=4, ncol=len(cols))
aois = ["Sensodyne_Products", "Sensodyne_POSM_Wing", "Competitor_A", "Competitor_B", "Price_Tags", "Shelf_Other"]
r = 5
summary_rows = {}
for a in aois:
    for g in ("NoPOSM", "POSM"):
        if a == "Sensodyne_POSM_Wing" and g == "NoPOSM":
            continue
        ws.cell(row=r, column=1, value=a)
        ws.cell(row=r, column=2, value=g)
        crit = f'{R_GROUP},$B{r},{R_AOI},$A{r},{R_KEEP},"Yes"'
        ws.cell(row=r, column=3, value=f"=COUNTIFS({crit})")
        ws.cell(row=r, column=4, value=f"=100*AVERAGEIFS({R_FIX},{crit})")
        ws.cell(row=r, column=5, value=f'=COUNTIFS({crit},{R_TTFF},">0")')
        ws.cell(row=r, column=6, value=f"=AVERAGEIFS({R_TTFF},{crit})")
        # Array formula: SD of TTFF_s over rows matching condition, AOI, kept, and numeric TTFF
        ws.cell(row=r, column=7).value = ArrayFormula(
            f"G{r}",
            f'=_xlfn.STDEV.S(IF(({R_GROUP}=$B{r})*({R_AOI}=$A{r})*({R_KEEP}="Yes")*ISNUMBER({R_TTFF}),{R_TTFF}))')
        ws.cell(row=r, column=8, value=f"=AVERAGEIFS({R_DWELL},{crit})")
        ws.cell(row=r, column=9).value = ArrayFormula(
            f"I{r}",
            f'=_xlfn.STDEV.S(IF(({R_GROUP}=$B{r})*({R_AOI}=$A{r})*({R_KEEP}="Yes"),{R_DWELL}))')
        ws.cell(row=r, column=10, value=f"=AVERAGEIFS({R_FIXCOUNT},{crit})")
        for c in range(1, 11):
            ws.cell(row=r, column=c).border = box
            if c >= 3:
                ws.cell(row=r, column=c).number_format = "0.00"
        summary_rows[(a, g)] = r
        r += 1
sum_last = r - 1
ws["A%d" % (sum_last + 2)] = ("Array formulas (columns G and I): Excel 365 evaluates them with Enter; "
                              "Excel 2019 or older needs Ctrl+Shift+Enter after editing.")
ws["A%d" % (sum_last + 2)].font = note_font
autowidth(ws, max_w=22)
ws.column_dimensions["A"].width = 22

# Clustered bar chart of dwell share by AOI and condition, built from a small
# chart table (one row per AOI, one column per condition)
ct = sum_last + 5
ws.cell(row=ct - 1, column=1, value="Chart table: mean Dwell time (%) by AOI and condition").font = bold
ws.cell(row=ct, column=1, value="AOI"); ws.cell(row=ct, column=2, value="NoPOSM"); ws.cell(row=ct, column=3, value="POSM")
for i, a in enumerate(aois, start=1):
    ws.cell(row=ct + i, column=1, value=a)
    for j, g in enumerate(("NoPOSM", "POSM"), start=2):
        if (a, g) in summary_rows:
            ws.cell(row=ct + i, column=j, value=f"=H{summary_rows[(a, g)]}")
        else:
            ws.cell(row=ct + i, column=j, value=0)
        ws.cell(row=ct + i, column=j).number_format = "0.0"
chart = BarChart()
chart.type = "bar"; chart.grouping = "clustered"; chart.style = 10
chart.title = "Mean dwell time share by AOI and condition (SIMULATED)"
chart.x_axis.title = "AOI"; chart.y_axis.title = "Dwell time (% of shelf exposure)"
data = Reference(ws, min_col=2, max_col=3, min_row=ct, max_row=ct + len(aois))
cats = Reference(ws, min_col=1, min_row=ct + 1, max_row=ct + len(aois))
chart.add_data(data, titles_from_data=True); chart.set_categories(cats)
chart.series[0].graphicalProperties.solidFill = GRAY
chart.series[1].graphicalProperties.solidFill = NAVY
chart.height = 9; chart.width = 18
ws.add_chart(chart, f"E{ct - 1}")

# ---------------------------------------------------------------- Sensodyne
ws = wb.create_sheet("Sensodyne")
ws["A1"] = "Sensodyne_Products rows, kept respondents, sorted by condition (POSM first). SIMULATED data."
ws["A1"].font = Font(bold=True, size=12, color=NAVY)
ws["A2"] = ("In Excel: Data sheet > filter AOI Name = Sensodyne_Products and Keep = Yes > copy the visible "
            "rows here > sort by Group. T.TEST needs two blocks of numbers, so each condition must be contiguous.")
ws["A2"].font = note_font
sens_cols = ["Respondent Name", "Group", "Valid data", "TTFF parent (ms)", "TTFF_s", "Dwell time (%)", "Dwell_pct_clean",
             "Fixation count"]
ws.append([]); ws.append(sens_cols)
style_header(ws, row=4, ncol=len(sens_cols))
idx = {h: i for i, h in enumerate(header)}
sens = [rw for rw in rows if rw[idx["AOI Name"]] == "Sensodyne_Products" and float(rw[idx["Valid data"]]) >= 70]
sens.sort(key=lambda rw: (0 if rw[idx["Group"]] == "POSM" else 1, rw[idx["Respondent Name"]]))
r = 5
posm_rows, noposm_rows = [], []
for rw in sens:
    ttff = to_cell(rw[idx["TTFF parent (ms)"]]); dw = to_cell(rw[idx["Dwell time (%)"]])
    ws.cell(row=r, column=1, value=rw[idx["Respondent Name"]])
    ws.cell(row=r, column=2, value=rw[idx["Group"]])
    ws.cell(row=r, column=3, value=to_cell(rw[idx["Valid data"]]))
    ws.cell(row=r, column=4, value=ttff)
    ws.cell(row=r, column=5, value=f'=IF(ISNUMBER(D{r}),D{r}/1000,"")')
    ws.cell(row=r, column=6, value=dw)
    ws.cell(row=r, column=7, value=f"=IF(ISNUMBER(F{r}),F{r},0)")
    ws.cell(row=r, column=8, value=to_cell(rw[idx["Fixation count"]]))
    (posm_rows if rw[idx["Group"]] == "POSM" else noposm_rows).append(r)
    for c in range(1, 9):
        ws.cell(row=r, column=c).border = box
    r += 1
p1, p2 = posm_rows[0], posm_rows[-1]
n1, n2 = noposm_rows[0], noposm_rows[-1]
TP, TN = f"E{p1}:E{p2}", f"E{n1}:E{n2}"       # TTFF_s blocks
DP, DN = f"G{p1}:G{p2}", f"G{n1}:G{n2}"       # dwell share blocks

# Test block: columns J to M. Rows are assigned as we go and formulas refer to
# them by name, so nothing is off by one.
t0 = 4
ws.cell(row=t0, column=10, value="Statistic").font = hdr_font
ws.cell(row=t0, column=11, value="Value").font = hdr_font
ws.cell(row=t0, column=12, value="Formula shown").font = hdr_font
ws.cell(row=t0, column=13, value="Note").font = hdr_font
for c in (10, 11, 12, 13):
    ws.cell(row=t0, column=c).fill = hdr_fill

row_ptr = [t0 + 1]
ref = {}


def put(key, label, formula=None, note="", fmt="0.0000"):
    """Write one statistic row; formula may contain {name} placeholders for earlier rows."""
    i = row_ptr[0]
    ws.cell(row=i, column=10, value=label)
    if formula is None:
        if label:
            ws.cell(row=i, column=10).font = bold
            ws.cell(row=i, column=10).fill = sub_fill
    else:
        f = formula.format(**{k: f"K{v}" for k, v in ref.items()})
        ws.cell(row=i, column=11, value=f).number_format = fmt
        ws.cell(row=i, column=12, value=f[1:])
        ws.cell(row=i, column=12).font = Font(name="Consolas", size=9, color="555555")
        if note:
            ws.cell(row=i, column=13, value=note).font = note_font
    if key:
        ref[key] = i
    row_ptr[0] += 1
    return i


def two_group_block(prefix, title, A, B, unit, note_n=""):
    """Write a Welch t test and Cohen's d block. In the formulas, {@x} stands for
    the Value cell of the row named prefix + x."""
    P = lambda f: f.replace("{@", "{" + prefix)
    put(None, title)
    put(prefix + "m1", f"POSM mean ({unit})", f"=AVERAGE({A})", "AVERAGE of the POSM block")
    put(prefix + "s1", f"POSM SD ({unit})", f"=_xlfn.STDEV.S({A})", "STDEV.S = sample standard deviation")
    put(prefix + "n1", "POSM n", f"=COUNT({A})", note_n, fmt="0")
    put(prefix + "m2", f"NoPOSM mean ({unit})", f"=AVERAGE({B})")
    put(prefix + "s2", f"NoPOSM SD ({unit})", f"=_xlfn.STDEV.S({B})")
    put(prefix + "n2", "NoPOSM n", f"=COUNT({B})", fmt="0")
    put(prefix + "diff", f"Difference POSM minus NoPOSM ({unit})", P("={@m1}-{@m2}"))
    put(prefix + "t", "Welch t", P("=({@m1}-{@m2})/SQRT({@s1}^2/{@n1}+{@s2}^2/{@n2})"),
        "t = (M1 - M2) / sqrt(s1^2/n1 + s2^2/n2)")
    put(prefix + "df", "Welch df",
        P("=({@s1}^2/{@n1}+{@s2}^2/{@n2})^2/(({@s1}^2/{@n1})^2/({@n1}-1)+({@s2}^2/{@n2})^2/({@n2}-1))"),
        "Welch Satterthwaite degrees of freedom", fmt="0.00")
    put(prefix + "p", "p, two tailed (T.TEST type 3)", f"=_xlfn.T.TEST({A},{B},2,3)",
        "tails = 2, type = 3 means unequal variances (Welch)")
    put(prefix + "p2", "p from the hand computed t", P("=_xlfn.T.DIST.2T(ABS({@t}),{@df})"),
        "should match the T.TEST cell")
    put(prefix + "sp", "Pooled SD", P("=SQRT((({@n1}-1)*{@s1}^2+({@n2}-1)*{@s2}^2)/({@n1}+{@n2}-2))"),
        "sp = sqrt(((n1 - 1) s1^2 + (n2 - 1) s2^2) / (n1 + n2 - 2))")
    put(prefix + "d", "Cohen's d", P("={@diff}/{@sp}"), "d = (M1 - M2) / sp")
    put(prefix + "se", "SE of d (approximation)",
        P("=SQRT(({@n1}+{@n2})/({@n1}*{@n2})+{@d}^2/(2*({@n1}+{@n2})))"),
        "sqrt((n1 + n2) / (n1 n2) + d^2 / (2 (n1 + n2)))")
    put(prefix + "lo", "d 95% CI lower", P("={@d}-1.96*{@se}"),
        "large sample approximation; R uses the noncentral t interval")
    put(prefix + "hi", "d 95% CI upper", P("={@d}+1.96*{@se}"))
    put(None, "")


two_group_block("t_", "Welch t test and Cohen's d: TTFF_s to Sensodyne_Products", TP, TN, "s",
                "COUNT ignores blanks and text, so never fixated rows drop out")
two_group_block("d_", "Welch t test and Cohen's d: Dwell time (%) on Sensodyne_Products", DP, DN, "%",
                "never fixated rows count as 0 here")
ws.column_dimensions["J"].width = 44; ws.column_dimensions["K"].width = 12
ws.column_dimensions["L"].width = 60; ws.column_dimensions["M"].width = 52
for col in "ABCDEFGH":
    ws.column_dimensions[col].width = 16

# Bar chart of mean TTFF by condition with 95 percent CI error bars
ws.cell(row=42, column=10, value="Chart table: mean TTFF_s with 95% CI half width").font = bold
ws.cell(row=43, column=10, value="Condition"); ws.cell(row=43, column=11, value="Mean TTFF (s)"); ws.cell(row=43, column=12, value="CI half width")
ws.cell(row=44, column=10, value="NoPOSM"); ws.cell(row=44, column=11, value=f"=K{ref['t_m2']}")
ws.cell(row=44, column=12, value=f"=_xlfn.CONFIDENCE.T(0.05,K{ref['t_s2']},K{ref['t_n2']})")
ws.cell(row=45, column=10, value="POSM");   ws.cell(row=45, column=11, value=f"=K{ref['t_m1']}")
ws.cell(row=45, column=12, value=f"=_xlfn.CONFIDENCE.T(0.05,K{ref['t_s1']},K{ref['t_n1']})")
for rr in (44, 45):
    ws.cell(row=rr, column=11).number_format = "0.00"; ws.cell(row=rr, column=12).number_format = "0.00"
chart2 = BarChart()
chart2.type = "col"; chart2.style = 10
chart2.title = "Mean TTFF to Sensodyne_Products by condition (SIMULATED)"
chart2.y_axis.title = "TTFF parent (s)"; chart2.x_axis.title = None
data2 = Reference(ws, min_col=11, min_row=43, max_row=45)
cats2 = Reference(ws, min_col=10, min_row=44, max_row=45)
chart2.add_data(data2, titles_from_data=True); chart2.set_categories(cats2)
chart2.series[0].graphicalProperties.solidFill = NAVY
eb = ErrorBars(errDir="y", errBarType="both", errValType="cust",
               plus=NumDataSource(numRef=NumRef(f="Sensodyne!$L$44:$L$45")),
               minus=NumDataSource(numRef=NumRef(f="Sensodyne!$L$44:$L$45")))
chart2.series[0].errBars = eb
chart2.legend = None
chart2.height = 8; chart2.width = 12
ws.add_chart(chart2, "N42")

# ---------------------------------------------------------------- Survey
sh, srows = read_csv("SIMULATED_shelf_study_survey.csv")
ws = wb.create_sheet("Survey")
ws["A1"] = "Survey after the glasses came off, joined to Sensodyne dwell share. SIMULATED data."
ws["A1"].font = Font(bold=True, size=12, color=NAVY)
ws.append([])
ws.append(sh + ["Keep", "Sensodyne dwell (%)"])
style_header(ws, row=3, ncol=len(sh) + 2)
sidx = {h: i for i, h in enumerate(sh)}
srows.sort(key=lambda rw: (0 if rw[sidx["Group"]] == "POSM" else 1, rw[sidx["Respondent Name"]]))
r = 4
sv_posm, sv_noposm = [], []
for rw in srows:
    for c, v in enumerate(rw, start=1):
        ws.cell(row=r, column=c, value=to_cell(v))
    rid = rw[sidx["Respondent Name"]]
    # Keep flag and dwell share pulled from the Sensodyne sheet with INDEX/MATCH
    ws.cell(row=r, column=7, value=f'=IF(ISNA(MATCH(B{r},Sensodyne!$A$5:$A$40,0)),"No","Yes")')
    ws.cell(row=r, column=8, value=f'=IFERROR(INDEX(Sensodyne!$G$5:$G$40,MATCH(B{r},Sensodyne!$A$5:$A$40,0)),"")')
    ws.cell(row=r, column=8).number_format = "0.00"
    (sv_posm if rw[sidx["Group"]] == "POSM" else sv_noposm).append(r)
    r += 1
sv_last = r - 1
# Purchase intent blocks must exclude the excluded respondent: use a helper column
ws.cell(row=3, column=9, value="PI if kept").font = hdr_font; ws.cell(row=3, column=9).fill = hdr_fill
for rr in range(4, sv_last + 1):
    ws.cell(row=rr, column=9, value=f'=IF(G{rr}="Yes",D{rr},"")')
PP = f"I{sv_posm[0]}:I{sv_posm[-1]}"; PN = f"I{sv_noposm[0]}:I{sv_noposm[-1]}"
tests = [
    ("Purchase intent, POSM mean", f"=AVERAGE({PP})"),
    ("Purchase intent, POSM SD", f"=_xlfn.STDEV.S({PP})"),
    ("Purchase intent, POSM n", f"=COUNT({PP})"),
    ("Purchase intent, NoPOSM mean", f"=AVERAGE({PN})"),
    ("Purchase intent, NoPOSM SD", f"=_xlfn.STDEV.S({PN})"),
    ("Purchase intent, NoPOSM n", f"=COUNT({PN})"),
    ("p, Welch T.TEST (2 tails, type 3)", f"=_xlfn.T.TEST({PP},{PN},2,3)"),
    ("Cohen's d (pooled SD)", "=(L4-L7)/SQRT(((L6-1)*L5^2+(L9-1)*L8^2)/(L6+L9-2))"),
    ("Brand recall Yes, POSM (count)", f'=COUNTIFS(C4:C{sv_last},"POSM",E4:E{sv_last},"Yes",G4:G{sv_last},"Yes")'),
    ("Brand recall Yes, NoPOSM (count)", f'=COUNTIFS(C4:C{sv_last},"NoPOSM",E4:E{sv_last},"Yes",G4:G{sv_last},"Yes")'),
    ("Chose Sensodyne, POSM (count)", f'=COUNTIFS(C4:C{sv_last},"POSM",F4:F{sv_last},"Sensodyne",G4:G{sv_last},"Yes")'),
    ("Chose Sensodyne, NoPOSM (count)", f'=COUNTIFS(C4:C{sv_last},"NoPOSM",F4:F{sv_last},"Sensodyne",G4:G{sv_last},"Yes")'),
    ("CORREL: Sensodyne dwell (%) with purchase intent (kept)", f"=CORREL(H4:H{sv_last},I4:I{sv_last})"),
]
ws.cell(row=3, column=11, value="Statistic").font = hdr_font; ws.cell(row=3, column=11).fill = hdr_fill
ws.cell(row=3, column=12, value="Value").font = hdr_font; ws.cell(row=3, column=12).fill = hdr_fill
for i, (lab, f) in enumerate(tests, start=4):
    ws.cell(row=i, column=11, value=lab)
    ws.cell(row=i, column=12, value=f).number_format = "0.000"
ws.column_dimensions["K"].width = 52; ws.column_dimensions["L"].width = 12
autowidth(ws, max_w=36)
ws.column_dimensions["K"].width = 52

# ---------------------------------------------------------------- Check
ws = wb.create_sheet("Check")
ws["A1"] = "Reference values from analysis.R (SIMULATED data). Your Excel formulas should match to rounding."
ws["A1"].font = Font(bold=True, size=12, color=NAVY)
ws.append([])
th, trows = read_csv("SIMULATED_test_results.csv")
ws.append(th)
style_header(ws, row=3, ncol=len(th))
for rw in trows:
    ws.append([to_cell(v) for v in rw])
ws.append([])
ws.append(["Note: R reports the Cohen's d interval from the noncentral t distribution (effectsize package);",
           ])
ws.append(["the Excel sheet uses the large sample approximation, so the CI limits differ a little while d itself matches."])
ws.append([])
dh, drows = read_csv("SIMULATED_descriptives_by_condition_AOI.csv")
start = ws.max_row + 1
ws.append(dh)
style_header(ws, row=start, ncol=len(dh))
for rw in drows:
    ws.append([to_cell(v) for v in rw])
autowidth(ws, max_w=34)

wb.save(OUT)
print("wrote", OUT)
